## This file is a template remove the .template to use the file

libraries:                       # This is called out once within the config.yml file
  Movies:                        # Each library must match the Plex library name
    collection_files:
    - default: basic                 # This is a file within the defaults folder in the Repository
    - default: imdb                  # This is a file within the defaults folder in the Repository
      template_variables:
        use_lowest: false
        visible_library_top: true
        visible_home_top: true
        visible_shared_top: true
    - default: streaming
      template_variables:
        collection_order: release
    - default: universe
      template_variables:
        collection_order: release
        exclude: dcu
        append_data:
          dcs: DC Studios
        trakt_list_askew: https://trakt.tv/users/jes-wan/lists/view-askewniverse?sort=released,desc
        mdblist_list_avp: https://mdblist.com/lists/exoduso/predator-franchise
        trakt_list_dca: https://trakt.tv/users/sergeyhist/lists/dc-animation?sort=released,asc
        mdblist_list_dcs: https://mdblist.com/lists/lookshinji/dc-studios
        mdblist_list_marvel: https://mdblist.com/lists/fa11en82/in-association-with-marvel
        mdblist_list_mcu: https://mdblist.com/lists/mmozeiko/marvel-cinematic-universe
        mdblist_list_middle: https://mdblist.com/lists/andyhawks/universe-middle-earth
        mdblist_list_star: https://mdblist.com/lists/lookshinji/star-wars-universe
        mdblist_list_trek: https://mdblist.com/lists/lookshinji/star-trek
        mdblist_list_xmen: https://mdblist.com/lists/venkatjampani/xmen-x9ul57pzlt
    - default: seasonal
      template_variables:
        emoji: ''
        collection_section: '025'
    - default: based
      template_variables:
        collection_order: release.desc
    - default: separator_award
    - default: oscars
      template_variables:
        use_year_collections: false
        collection_order: release.desc
    - default: bafta
      template_variables:
        use_year_collections: false
        collection_order: release.desc
    - default: nfr
      template_variables:
        use_year_collections: false
        collection_order: release.desc
    - default: franchise
      template_variables:
        collection_mode: default
        movie_10522: # Starship Troopers Collection
        - 563:      # Starship Troopers
        - 10304:    # Starship Troopers 2: Hero of the Federation
        - 11127:    # Starship Troopers 3: Marauder
        - 114478:   # Starship Troopers: Invasion
        - 460790:   # Starship Troopers: Traitor of Mars
        exclude:
        - 192492    # The Jack Ryan Collection
        - 1445665   # Starship Troopers (Animated) Collection
        - 893713    # Sword Art Online Collection
        - 388790    # Heaven's Lost Property Collection
        - 118415    # Berserk: Golden Age Arc Collection
        - 383987    # Attack on Titan: Animation Collection
        - 961121    # Eureka Seven Hi-Evolution Collection
        - 91697     # Battlestar Galactica (Reboot) Collection
        - 754601    # LUPIN THE IIIRD Collection
        - 1143843   # Lupin the Third vs Detective Conan Collection
        - 1185967   # Lupin the Third Collection
        - 23497     # Bleach Collection
        - 261590    # Living Dead Collection
        - 944437    # Survival of the Dead Collection
        - 9743      # The Hannibal Lecter Collection
    - folder: config/moviecollections
      # see the wiki for how to use local files, folders, URLs, or files from git
    remove_overlays: false            ## <<< ADD THIS LINE
    overlay_files:                         ## <<< ADD THIS LINE
    - default: resolution
      template_variables:
        use_4k_dvhdrplus: true
        use_4k_dvhdr: true
        use_4k_plus: true
        use_4k_dv: true
        use_4k_hlg: true
        use_4k_hdr: true
        use_4k: true
        use_1080p_dvhdrplus: false
        use_1080p_dvhdr: false
        use_1080p_plus: false
        use_1080p_dv: false
        use_1080p_hlg: false
        use_1080p_hdr: false
        use_1080p: false
        use_720p: false
        use_576p: false
        use_480p: false
        use_edition: false
    operations:
      assets_for_all: true
  TV Shows:
    collection_files:
    - default: basic                   # This is a file within Kometa's defaults folder
    - default: imdb                    # This is a file within Kometa's defaults folder
    - default: streaming
      template_variables:
        collection_order: release
    - default: universe
      template_variables:
        collection_order: release
        exclude: dcu
        append_data:
          dcs: DC Studios
          twd: The Walking Dead
        mdblist_list_arrow: https://mdblist.com/lists/lookshinji/arrowverse
        mdblist_list_avp: https://mdblist.com/lists/exoduso/predator-franchise
        trakt_list_dca: https://trakt.tv/users/sergeyhist/lists/dc-animation?sort=released,asc
        mdblist_list_dcs: https://mdblist.com/lists/lookshinji/dc-studios
        mdblist_list_marvel: https://mdblist.com/lists/fa11en82/in-association-with-marvel
        mdblist_list_mcu: https://mdblist.com/lists/mmozeiko/marvel-cinematic-universe
        mdblist_list_middle: https://mdblist.com/lists/kayaaron13/middle-earth
        mdblist_list_star: https://mdblist.com/lists/lookshinji/star-wars-universe
        mdblist_list_trek: https://mdblist.com/lists/lookshinji/star-trek
        trakt_list_twd: https://trakt.tv/users/myrobin/lists/walking-dead?sort=rank,asc
        mdblist_list_xmen: https://mdblist.com/lists/venkatjampani/xmen-x9ul57pzlt
    - default: separator_award
    - default: emmy
      template_variables:
        use_year_collections: false
        collection_order: release.desc
    - default: golden
      template_variables:
        use_year_collections: false
        collection_order: release.desc
    - default: choice
      template_variables:
        use_year_collections: false
        collection_order: release.desc
    - default: pca
      template_variables:
        use_year_collections: false
        collection_order: release.desc
    - default: sag
      template_variables:
        use_year_collections: false
        collection_order: release.desc
    - default: based
      template_variables:
        collection_order: release.desc
    - folder: config/tvcollections
      # see the wiki for how to use local files, folders, URLs, or files from git
    remove_overlays: false            ## <<< ADD THIS LINE
    overlay_files:
    - default: resolution
      template_variables:
        use_4k_dvhdrplus: true
        use_4k_dvhdr: true
        use_4k_plus: true
        use_4k_dv: true
        use_4k_hdr: true
        use_4k: true
        use_1080p: false
        use_720p: false
        use_576p: false
        use_480p: false
    - default: resolution
      template_variables:
        builder_level: season
        use_4k: true
        use_1080p: false
        use_720p: false
        use_576p: false
        use_480p: false
      # see the wiki for how to use local files, folders, URLs, or files from git
    operations:
      assets_for_all: true
  Anime:
    collection_files:
    - default: basic                   # This is a file within Kometa's defaults folder
    - default: anilist                 # This is a file within Kometa's defaults folder
    - default: myanimelist             # This is a file within Kometa's defaults folder
      template_variables:
        mal_airing: true
        mal_all: true
        mal_favorite: true
        mal_popular: true
        mal_season: true
    - default: other_chart             # This is a file within Kometa's defaults folder
      template_variables:
        use_anidb: true
        use_commonsense: false
        use_stevenlu: false
        use_pirated: false
    - default: streaming
      exclude: showtime
      template_variables:
        collection_order: release
    - folder: config/animecollections
      # see the wiki for how to use local files, folders, URLs, or files from git
    remove_overlays: false            ## <<< ADD THIS LINE
    overlay_files:
    - default: language_count
      template_variables:
        builder_level: episode
    operations:
      assets_for_all: true
playlist_files:
- file: config/playlistcollection.yml
  # see the wiki for how to use local files, folders, URLs, or files from git
settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  cache: true
  cache_expiration: 15
  asset_directory:
  - /config/assets/Anime
  - /config/assets/Collections
  - /config/assets/Movies
  - /config/assets/TV Shows
  asset_folders: false
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 2
  default_collection_order:
  delete_below_minimum: false
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: true
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  overlay_artwork_filetype: jpg
  overlay_artwork_quality:
  show_unfiltered: false
  webhooks:                          # Can be individually specified per library as well
  changes:
  delete:
  error:
  run_end:
  run_start:
  version:
tautulli:                          # Can be individually specified per library as well
  url: http://192.168.1.12:8181    # Enter Tautulli URL (Optional)
  apikey:                          # Enter Tautulli API Key (Optional)
github:
  token:                           # Enter GitHub Personal Access Token (Optional)
omdb:
  apikey:                          # Enter OMDb API Key (Optional)
  cache_expiration: 60
mdblist:
  apikey:                          # Enter MDBList API Key (Optional)
  cache_expiration: 60
notifiarr:
  apikey:                          # Enter Notifiarr API Key (Optional)
gotify:
  url: http://192.168.1.12:80      # Enter Gotify server URL (Optional)
  token:                           # Enter Gotify Token (Optional)
ntfy:
  url: http://192.168.1.12:80      # Enter ntfy server URL (Optional)
  token:                           # Enter ntfy Access Token (Optional)
  topic:                           # Enter ntfy Topic (Optional)
anidb:
  cache_expiration: 60
  language: en
  enable_mature: false
radarr:                            # Can be individually specified per library as well
  url: http://192.168.1.12:7878    # Enter Radarr server URL (Optional)
  token:                           # Enter Radarr API Key (Optional)
  add_missing: false
  add_existing: false
  upgrade_existing: false
  monitor_existing: false
  root_folder_path: "S:/Movies"    # This value is CASE SENSITIVE
  monitor: true
  availability: announced
  quality_profile: HD-1080p        # This value is CASE SENSITIVE
  tag:
  search: false
  radarr_path:                    # This value is only needed in combination with the *_existing settings
  plex_path:                      # This value is only needed in combination with the *_existing settings
  ignore_cache: false
sonarr:                            # Can be individually specified per library as well
  url: http://192.168.1.12:8989    # Enter Sonarr server URL (Optional)
  token:                           # Enter Sonarr API Key (Optional)
  add_missing: false
  add_existing: false
  upgrade_existing: false
  monitor_existing: false
  root_folder_path: "S:/TV Shows"  # This value is CASE SENSITIVE
  monitor: all
  quality_profile: HD-1080p        # This value is CASE SENSITIVE
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:                     # This value is only needed in combination with the *_existing settings
  plex_path:                       # This value is only needed in combination with the *_existing settings
  ignore_cache: false
trakt:
  client_id:                       # Enter Trakt Client ID (Optional)
  client_secret:                   # Enter Trakt Client Secret (Optional)
  pin:
  authorization:
                                   # authorization section is autofilled by the script
    access_token:
    created_at:
    expires_in:
    refresh_token:
    scope: public
    token_type:
mal:
  client_id:                       # Enter MyAnimeList Client ID (Optional)
  client_secret:                   # Enter MyAnimeList Client Secret (Optional)
  cache_expiration: 60
  localhost_url:
  authorization:
                                   # authorization section is autofilled by the script
    access_token:
    expires_in:
    refresh_token:
    token_type:
